= Uso da crase

Crase é o nome que se dá à união da preposição “a” com o artigo definido “a(s)”, ou com o “a” inicial dos pronomes demonstrativos “aquele(s)”, “aquela(s)” e “aquilo”, ou, ainda, com o “a” inicial dos pronomes relativos “a qual” e “as quais”.

Ao acento indicador de crase dá-se o nome de acento grave. No entanto, existem algumas regras para usar a crase e alguns macetes para nunca deixar de fazer o seu uso correto. É o que veremos a seguir.

Quando usar a crase?
Quando o complemento de um verbo que exija a preposição “a” for um substantivo feminino antecedido de artigo feminino “a”:

Vamos à loja para comprar outros enfeites.

Observe: Vamos a + a loja = Vamos à loja.

Quando o complemento de um nome que exija a preposição “a” for um substantivo feminino antecedido de artigo feminino “a”:

Ela se mostrou favorável à medida proposta pela vereadora.

Observe: Ela se mostrou favorável a + a medida = Ela se mostrou favorável à medida.

Quando os pronomes demonstrativos “aquele(s)”, “aquela(s)” e “aquilo” exercem a função de complemento de termo que exija a preposição “a”:

Somos contrários àqueles que defendem o radicalismo.

Devo obedecer àquilo em que acredito.

Estou referindo-me àquelas semanas em que não pude vir trabalhar.

Portanto:

Somos contrários a + aqueles = Somos contrários àqueles.

Devo obedecer a + aquilo = Devo obedecer àquilo.

Estou referindo-me a + aquelas = Estou referindo-me àquelas.

Atenção! O pronome demonstrativo pode estar implícito (oculto). Nesse caso, ocorre a crase:

Não me refiro a essa, mas à da direita.

Observe: Não me refiro a essa, mas a (aquela) da direita = Não me refiro a essa, mas àquela da direita.

Quando os pronomes relativos “a qual” e “as quais” exercem a função de complemento de termo que exija a preposição “a”:

A peça à qual assisti não valeu um centavo do que paguei.

As tarefas às quais nos dedicamos cotidianamente são sempre essenciais.

Assim:

Assisti a + a peça = Assisti à peça.

Dedicamo-nos a + as tarefas = Dedicamo-nos às tarefas.

No entanto, o pronome “a qual” se refere ao termo anterior “peça”, no primeiro exemplo, e o pronome “as quais” se refere ao termo anterior “tarefas”, no segundo exemplo. Nesse caso, o acento grave é colocado sobre o “a” dos pronomes relativos “a qual” e “as quais”. Portanto: “A peça à qual assisti” e “As tarefas às quais nos dedicamos”.

Leia também: A ou há?

Em locuções adverbiais femininas com substantivos no singular ou plural, como: à tarde, à vontade, às vezes, às pressas, às quatro horas etc.:

Vocês estão em minha casa, podem ficar à vontade.

Não vale a pena decidir às pressas o que fazer nas férias.

Exceção à regra é a locução “a distância”, se não estiver determinada:

Estávamos observando tudo a distância.

Estávamos observando tudo à distância de cinco metros.

Nas locuções conjuntivas “à medida que” e “à proporção que”:

À medida que amadurecemos, passamos a dar valor ao silêncio.

Antes de palavra masculina (inclusive no plural), caso haja uma palavra feminina implícita:

Necessitamos, com urgência, ir à abastecimentos.

Isto é: Necessitamos, com urgência, ir à (central de) abastecimentos.

Quando não usar a crase?
Antes de verbos:

Meu primo começou a cumprir pena socioeducativa.

Antes de pronome pessoal:

Não tenho que dar satisfações a ela.

Veja também: Pronomes de tratamento – um tipo específico de pronome pessoal

Antes de palavras masculinas:

Era um sentimento muito semelhante ao amor.

Era um sentimento muito semelhante a amor.

Portanto, a próxima frase está incorreta:

Era um sentimento muito semelhante à amor.

Atenção! Pode ocorrer crase diante de palavra masculina quando ela for precedida de palavra feminina implícita na frase:

Era uma pintura à Leonardo da Vinci.

Entende-se:

Era uma pintura à (maneira de) Leonardo da Vinci.

Entre palavras idênticas repetidas, como nas expressões: cara a cara, boca a boca etc.:

Depois do afogamento, foi preciso fazer respiração boca a boca.

Antes das palavras “casa” (no sentido de “lar”) e “terra” (em sentido oposto a “bordo”):

Vou a casa no próximo fim de semana.

Ao chegar a terra, o marinheiro foi até o local marcado.

No entanto, se essas duas palavras (“casa” e “terra”) forem qualificadas, ocorrerá a crase:

Vou à casa de minha irmã no próximo fim de semana.

Ao chegar à terra dos renegados, o marinheiro foi até o local marcado.

Antes de palavra feminina de caráter genérico:

Não cheguei a conclusão alguma.

Não peço nenhum favor a pessoas de caráter duvidoso.

Antes de nome de cidade ou vila:

Chegar a Fortaleza é como voltar para casa.

Fiz referência a Jericoacoara em minha tese de doutorado.

Antes de nomes de pessoas famosas:

O artigo estava relacionado a Marie Curie.

Antes dos seguintes pronomes: “ninguém”, “essa”, “toda”, “cada”, “qualquer”, “tudo”:

Ela devia dar satisfações a toda a gente, a cada pessoa prejudicada.

Antes do artigo indefinido “uma”:

Não se deve dar crédito a uma pessoa que mente.

Antes de numerais:

Eles foram comparados a duas crianças mimadas.

Antes de expressões adverbiais de modo com substantivo no plural:

A trancos e barrancos, conseguiu chegar até o fim da maratona.

Os funcionários resolveram tudo a pauladas.

Depois da palavra “candidata”:

Luciana foi candidata a prefeita nas últimas eleições.

Casos facultativos de uso da crase
Antes de pronomes possessivos femininos:

Não dão valor à nossa opinião.

ou

Não dão valor a nossa opinião.

Antes de nome próprio feminino:

Fizemos referência a Joana.

ou

Fizemos referência à Joana.

José de Nicola e Ulisses Infante defendem que, nesse caso, o uso do artigo “a” é facultativo. Segundo eles, uma forma de verificar isso é substituir, na frase, o termo que exige a preposição “a” por um termo que exige outro tipo de preposição. Veja um exemplo:

Não falamos da Joana

ou

Não falamos de Joana.

Isso, de acordo com esses gramáticos, demonstra que o uso do artigo é facultativo; consequentemente, o uso da crase também.

Já Luiz Antonio Sacconi defende que só “acentuamos o ‘a’ antes de nomes de pessoas quando se tratar de indivíduo que faça parte do nosso círculo de amizades, indivíduos aos quais damos tratamento íntimo: a Marisa, a Bete, a Rosa etc. Ex.: Refiro-me à Marisa, e não à Bete”. No entanto, apesar disso, ele considera esse uso facultativo.

Antes de locuções adverbiais femininas indicativas de instrumento, em regra, não se deve utilizar a crase:

Não se pode resolver os conflitos a bala.

No entanto, muitos gramáticos entendem que o uso do acento grave, nesses casos, é facultativo:

Não se pode resolver os conflitos à bala.

Antes dos seguintes nomes de lugar: Europa, Ásia, África, França, Inglaterra, Espanha, Holanda, Escócia e Flandres. Assim:

Não podemos mais voltar à Escócia.

ou

Não podemos mais voltar a Escócia.

Na locução prepositiva “até a”, antes de substantivo feminino:

Chegaram até a praia e desistiram de nadar.

ou

Chegaram até à praia e desistiram de nadar.

Dicas/macetes para o uso correto da crase
O principal macete para você descobrir se deve ou não usar a crase é substituir a palavra feminina que vem depois da possível crase por uma palavra masculina equivalente:

Eu cheguei à escola de Marcelo.

Façamos então a substituição:

Eu cheguei ao colégio de Marcelo.

Note que, ao fazer essa alteração, é possível perceber a presença do artigo definido masculino “o” antes do substantivo “colégio”, o que indica a presença do artigo definido feminino “a” antes do substantivo “escola”.

Assim, temos:

Eu cheguei a + a escola de Marcelo = Eu cheguei à escola de Marcelo.

Eu cheguei a + o colégio de Marcelo = Eu cheguei ao colégio de Marcelo.

Outro macete, semelhante ao primeiro, é substituir o artigo definido feminino “a” pelo artigo indefinido feminino “uma”. Se é possível utilizar esse segundo artigo, é porque a presença de um artigo feminino é necessária na frase:

Assisti à luta de boxe no último domingo.

Façamos a substituição:

Assisti a uma luta de boxe no último domingo.

Desse modo, temos:

Assisti a + a luta de boxe = Assisti à luta de boxe.

Assisti a + uma luta de boxe = Assisti a uma luta de boxe.

Outra maneira de ter certeza da ocorrência ou não da crase, no caso de verbos que indicam movimento, como “ir”, “chegar” etc., é substituir esses verbos por outros que indiquem procedência, como “vir”, “partir” etc., ou mesmo localização, como “estar”, “ficar” etc.:

Chegamos a Fortaleza na manhã de sábado.

Então substituímos por:

Partimos de Fortaleza na manhã de sábado.

E também por:

Ficamos em Fortaleza na manhã de sábado.

Perceba que, nas duas substituições, nota-se apenas a presença de preposição, mas não de artigo. Portanto, em “Chegamos a Fortaleza na manhã de sábado”, não pode ocorrer crase.

Veja também: Uso da vírgula – como usar esse importante sinal de pontuação.